# application-dev.yml
sky:
  datasource:  # 数据库配置（独立层级）
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1234  # 注意：数据库密码也建议用环境变量，避免硬编码

  alioss:  # OSS配置（与datasource同级，而非嵌套）
    access-key-id: ${ALIOSS_ACCESS_KEY_ID:}  # 读取环境变量
    access-key-secret: ${ALIOSS_ACCESS_KEY_SECRET:}
    endpoint: ${ALIOSS_ENDPOINT:}
    bucket-name: ${ALIOSS_BUCKET_NAME:}
  redis:
    host: localhost
    port: 6379
    #password: '123456'
    database: 10
  wechat:
    appid: ${SKY_WECHAT_APPID:}
    secret: ${SKY_WECHAT_SECRET:}
    mchid: 1561414331
    mchSerialNo: 4B3B3DC35414AD50B1B755BAF8DE9CC7CF407606
    #privateKeyFilePath: C:\software\apiclient_key.pem
    apiV3Key: CZBK51236435wxpay435434323FFDuv3
    #weChatPayCertFilePat: C:\software\wechatpay_166D96F876F45C7D07CE98952A96EC980368ACFC.pem
    notifyUrl: https://xxxxxxxx.xxx.cpolar.top/notify/paySuccess
    refundNotifyUrl: https://xxxxxxxx.xxx.cpolar.top/notify/refundSuccess
  shop:
    address: 北京市海淀区上地十街10号
  baidu:
    ak: ${BAIDU_AK:}
